########################################################################
#
#   Copyright (c) 2022 - 2024 Fraunhofer Institute of Optronics,
#   System Technologies and Image Exploitation IOSB
#
########################################################################

# Marker observation to add
MarkerObservations observation
---
# Flag, if is accepted or not
bool is_accepted

# Response message
string msg